version: '3'
services:
   rabbitmq:
      image: rabbitmq:3.7.13-management
      ports:
         - "5672:5672"
         - "15672:15672"
         - "5671:5671"
      restart: always
   web:
      image: kushguptacse/rabbitmq-producer-docker
      depends_on:
         - rabbitmq
      ports:
         - 8097:8097
      environment:
         SPRING_RABBITMQ_HOST: rabbitmq